### ISSUE TITLE
css 中包含 filter 声明时报错

### ISSUE THREAD

**Issue by sorrycc** [spmjs/spm-webpack#3]
csso 的问题，貌似没人维护了。。
https://github.com/css/csso/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+filter

比如：

``` css
a {
  filter:alpha(opacity=100 finishopacity=50 style=1 startx=0,starty=0,finishx=0,finishy=150) progid:dximagetransform.microsoft.gradient(startcolorstr=#fcfcfc,endcolorstr=#eeeeee,gradienttype=0);
}
```

出错：

``` bash
$ spm-webpack --debug
          start: build
         target: http://spmjs.io
          error: ./a.css
Module build failed: Error: Didn't get a result from child compiler
    at Object.<anonymous> (~/Documents/Work/Libraries/alipay/spm-family/spm-webpack/node_modules/extract-text-webpack-plugin/loader.js:90:22)
    at Tapable.<anonymous> (/Users/chencheng/Documents/Work/Libraries/alipay/webpack-family/webpack/lib/Compiler.js:212:10)
    at /Users/chencheng/Documents/Work/Libraries/alipay/webpack-family/webpack/lib/Compiler.js:400:12
    at Tapable.next (/Users/chencheng/Documents/Work/Libraries/alipay/webpack-family/webpack/node_modules/tapable/lib/Tapable.js:69:11)
    at Object.<anonymous> (/Users/chencheng/Documents/Work/Libraries/alipay/spm-family/spm-webpack/node_modules/extract-text-webpack-plugin/loader.js:77:5)
    at Tapable.next (/Users/chencheng/Documents/Work/Libraries/alipay/webpack-family/webpack/node_modules/tapable/lib/Tapable.js:71:37)
    at CachePlugin.<anonymous> (/Users/chencheng/Documents/Work/Libraries/alipay/webpack-family/webpack/lib/CachePlugin.js:40:4)
    at Tapable.applyPluginsAsync (/Users/chencheng/Documents/Work/Libraries/alipay/webpack-family/webpack/node_modules/tapable/lib/Tapable.js:73:13)
    at Tapable.<anonymous> (/Users/chencheng/Documents/Work/Libraries/alipay/webpack-family/webpack/lib/Compiler.js:397:9)
    at Tapable.<anonymous> (/Users/chencheng/Documents/Work/Libraries/alipay/webpack-family/webpack/lib/Compilation.js:548:13)
 @ ./a.js 1:0-18
```
